### ISSUE TITLE
new icon looks more 'light' and pale, not solid, so I declined

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cudatext_alt_icon#1]
@kvichans @OlehL @jairo-martinez @tmsg-gh 

![Screenshot from 2021-01-13 17-37-21](https://user-images.githubusercontent.com/4154978/104466251-12123200-55c6-11eb-8037-4fbc94eac80e.png)

**Comment by halfbrained** [comment]
"more 'light'" - about grey background?
"pale" - bottom of the characters?
I only ever see ~40px on taskbar, so it looks good there... are larger resolutions ever seen?

**Comment by Alexey-T** [comment]
more light== yellow stripe is flat, not 3d like before.
pale-- before it was more yellow.

**Comment by halfbrained** [comment]
> yellow stripe is flat, not 3d like before.  

Ha, that is the reason I decided to change it. I'll see if I can find a compromise

**Comment by Alexey-T** [comment]
Let's not spend time on this
