### ISSUE TITLE
need correction

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cudatext_alt_icon#2]
I'd want a flat icon. the icon needs some correction

- remove 'bright light from below', it must be full flat
- adjust colors: to look more 'official', maybe darker gray...

**Comment by halfbrained** [comment]
Any of these strike your fancy?  
<details><summary>spoiler</summary>  


<img src="https://user-images.githubusercontent.com/74829192/109422721-760d8000-79e5-11eb-8bc6-8193c4e825ec.png"/>


</details>

**Comment by Alexey-T** [comment]
yes,I like the 1st in 1st line, and 1st in 2nd line.

**Comment by halfbrained** [comment]
1024x1024 PNGs

https://github.com/halfbrained/cudatext_alt_icon/tree/main/main_flat

**Comment by Alexey-T** [comment]
thanks! posted this icon file (2-1.png) to my repo. note. for embedded app icon, i use different file cudatext.ico (it has n icons), not this PNG file.

**Comment by Alexey-T** [comment]
you can find cudatext.ico in Cud GH repo.

**Comment by halfbrained** [comment]
added [.ico](https://github.com/halfbrained/cudatext_alt_icon/blob/main/main_flat/2-1.ico) and [512x512](https://github.com/halfbrained/cudatext_alt_icon/blob/main/main_flat/2-1_512.png) version.

I'm glad you changed your mind :)

**Comment by halfbrained** [comment]
added [.ico](https://github.com/halfbrained/cudatext_alt_icon/blob/main/main_flat/2-1.ico) and [512x512](https://github.com/halfbrained/cudatext_alt_icon/blob/main/main_flat/2-1_512.png) version.

I'm glad you changed your mind :)

**Comment by Alexey-T** [comment]
applied both files. thanks!

**Comment by Alexey-T** [comment]
let's increase contrast. yellow and lite-gray have same lighness.
I take 1st in 4th line.
pls give the .ico and -512.png ? @halfbrained

**Comment by halfbrained** [comment]
Added [.ico](github.com/halfbrained/cudatext_alt_icon/blob/main/main_flat/4-1.ico) and [.png](https://github.com/halfbrained/cudatext_alt_icon/blob/main/main_flat/4-1.png)

**Comment by Alexey-T** [comment]
link bad (4-1.ico)but I got it. updated!
